blueprint:
  name: Lights Brightness Sync
  description: Synchronize brightness of child lights based on a parent light's brightness changes.
  domain: automation
  source_url: https://raw.githubusercontent.com/jeverley/home-assistant-blueprints/refs/heads/main/blueprints/automation/lights_brightness_sync.yaml
  input:
    parent_light:
      name: Parent light
      description: |
        The light whose brightness changes will control the child lights.
      selector:
        entity:
          multiple: false
          filter:
            - domain:
                - light
    child_lights:
      name: Child lights
      description: |
        Lights that will mirror the parent light's brightness changes.
      selector:
        entity:
          multiple: true
          filter:
            - domain:
                - light
    advanced:
      name: Advanced configuration
      description: |
        Optional settings for fine-tuning behavior.
      icon: mdi:cog
      collapsed: true
      input:
        ignore_internal_changes:
          name: Ignore Home Assistent changes
          description: |
            Ignore brightness changes triggered within Home Assistant (e.g., automations, scripts).
          default: true
          selector:
            boolean:
        transition:
          name: Transition
          description: |
            Duration it takes for child light brightness changes.
          default: 0.1
          selector:
            number:
              min: 0
              max: 1
              step: 0.1
              unit_of_measurement: "s"
        parent_min_pct:
          name: Parent minimum brightness % (optional)
          description: |
            Minimum brightness percentage at which the light is visibly on.
          default: 0
          selector:
            number:
              min: 1
              max: 100
              unit_of_measurement: "%"

trigger_variables:
  b_max: 255
  b_min: 1
  b_range: "{{ b_max - b_min }}"
  pct_to_b: "{{ b_max / 100 }}"
  child_lights: !input child_lights
  parent_light: !input parent_light
  parent_min_pct: !input parent_min_pct
  p_b_min: "{{ (parent_min_pct|default(0) * pct_to_b)|round }}"
  p_b_range: "{{ min(max(b_max - p_b_min, b_min), b_range) }}"

triggers:
  - trigger: state
    entity_id: !input parent_light
    attribute: brightness
    not_from:
      - null
      - 0
    not_to:
      - null
      - 0

conditions:
  - alias: If the state was changed by an external action
    condition: template
    enabled: !input ignore_internal_changes
    value_template: >
      {# Excludes state changes that were instigated within Home Assistant
      (i.e. Dashboards, Automations, Adaptive Lighting). #}

      {{
        trigger.to_state.context.user_id is none
        and (
          trigger.to_state.context.parent_id is none
          and trigger.to_state.context.id is not search(':al:.*:.*:')
        )
      }}

actions:
  - variables:
      from_brightness: |
        {{ int(trigger.from_state.attributes.brightness|default(none), 0) }}

  - repeat:
      sequence:
        - variables:
            from_brightness_adj: |
              {{ min(max(from_brightness - p_b_min, b_min) * b_range / p_b_range, b_max)|round }}
            to_brightness: |
              {{ int(state_attr(trigger.entity_id, 'brightness'), 0) }}
            to_brightness_adj: |
              {{ min(max(to_brightness - p_b_min, b_min) * b_range / p_b_range, b_max)|round }}
            change_abs: |
              {{ to_brightness_adj - from_brightness_adj }}

            child_scene: |
              {% set ns = namespace(scene={}) %}
              {% for state in expand(child_lights) %}
                {% set current = int(
                  child_scene[state.entity_id].brightness
                  if child_scene is defined and state.entity_id in child_scene
                  else state.attributes.brightness|default(none)
                  , 0
                ) %}
                {% if state.state == 'on' and current > 0 %}
                  {% set ns.scene = dict(ns.scene, **{state.entity_id: {
                    'state': 'on',
                    'brightness': max(min(current + change_abs, b_max), b_min),
                  }}) %}
                {% endif %}
              {% endfor %}
              {{ ns.scene }}

        - action: scene.apply
          metadata: {}
          data:
            entities: "{{ child_scene }}"
            transition: !input transition
        - variables:
            from_brightness: |
              {{ to_brightness }}

      until:
        - alias: Repeat until brightness stops changing
          condition: template
          value_template: |
            {{ state_attr(trigger.entity_id, 'brightness') in [to_brightness, none] }}

mode: single
max_exceeded: silent
