blueprint:
  name: LG webOS TV - Turn screen off/on with occupancy
  description: |
    Turns off an LG webOS TV screen when the area is unoccupied, turns on the screen when the area is occupied.
    This saves energy and reduces screen on time for OLED devices being used to play media in the background.

    Optionally shows a warning 5 seconds before turning the screen off.
  domain: automation
  input:
    tv_entity:
      name: TV
      selector:
        entity:
          multiple: false
          filter:
            - integration: webostv
              domain: media_player

    occupancy_sensor:
      name: Occupancy / Presence sensor
      selector:
        entity:
          multiple: false
          filter:
            - domain:
                - binary_sensor
              device_class:
                - occupancy
                - presence

    off_delay_s:
      name: Off delay
      description: The screen is turned off when the area is unoccupied for this duration
      default: 120
      selector:
        number:
          min: 0
          max: 300
          step: 1
          unit_of_measurement: s

    on_delay_s:
      name: On delay
      description: The screen is turned on when the area is occupied for this duration
      default: 0
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: s

    show_warning:
      name: Screen off warning
      description: Display a warning 5 seconds before the screen turns off
      default: false
      selector:
        boolean: {}

    warning_message:
      name: Warning message (optional)
      description: Custom message to show in the warning
      default: "The screen will turn off unless movement is detected"
      selector:
        text: {}

mode: restart

trigger_variables:
  tv_entity: !input tv_entity
  off_delay_s: !input off_delay_s
  show_warning: !input show_warning
  warning_delay: |
    {% if not show_warning or off_delay_s < 1 %}
      {{ none }}
    {% else %}
      {{ timedelta(seconds=(max(off_delay_s - 5, 0))) }}
    {% endif %}

trigger:
  - id: occupied
    platform: state
    entity_id: !input occupancy_sensor
    to: "on"
    for:
      seconds: !input on_delay_s

  - id: unoccupied
    platform: state
    entity_id: !input occupancy_sensor
    to: "off"
    for:
      seconds: !input off_delay_s

  - id: unoccupied_warning
    platform: state
    entity_id: !input occupancy_sensor
    to: "off"
    for: "{{ warning_delay }}"
    enabled: "{{ warning_delay is not none }}"

  - id: tv_available
    platform: state
    entity_id: !input tv_entity
    from:
      - unavailable
      - unknown
    not_to:
      - unavailable
      - unknown

condition:
  - alias: If the TV is ON
    condition: not
    conditions:
      - condition: state
        entity_id: !input tv_entity
        state:
          - "off"
          - unavailable
          - unknown

action:
  - alias: Stop if TV is OFF / unavailable
    if:
      - condition: state
        entity_id: !input tv_entity
        state:
          - "off"
          - unavailable
          - unknown
    then:
      - stop: "The TV is not ON"

  - alias: Get the current screen state (OFF / ON)
    service: webostv.command
    data:
      entity_id: !input tv_entity
      command: com.webos.service.tvpower/power/getPowerState
    response_variable: power_state
    continue_on_error: true
  - variables:
      power_state: |
        {% if power_state is not defined or not power_state[tv_entity].returnValue %}
          {{ none }}
        {% else %}
          {{ power_state[tv_entity].state != 'Screen Off' }}
        {% endif %}

  - choose:
      - alias: Warning
        conditions:
          - condition: trigger
            id: unoccupied_warning
          - alias: Screen is ON / unknown
            condition: template
            value_template: |
              {{ power_state in [true, none] }}
        sequence:
          - service: "{{ 'notify.' + device_name(tv_entity)|slugify }}"
            continue_on_error: true
            data:
              message: !input warning_message

      - alias: Turn OFF screen
        conditions:
          - condition: state
            entity_id: !input occupancy_sensor
            state: "off"
            for:
              seconds: !input off_delay_s
          - alias: Screen is ON / unknown
            condition: template
            value_template: |
              {{ power_state in [true, none] }}
        sequence:
          - service: webostv.command
            continue_on_error: true
            data:
              entity_id: !input tv_entity
              command: com.webos.service.tvpower/power/turnOffScreen

      - alias: Turn ON screen
        conditions:
          - or:
              - condition: state
                entity_id: !input occupancy_sensor
                state: "on"
                for:
                  seconds: !input on_delay_s
              - condition: state
                entity_id: !input occupancy_sensor
                state:
                  - unknown
                  - unavailable
          - alias: Screen is OFF / unknown
            condition: template
            value_template: |
              {{ not power_state }}
        sequence:
          - service: webostv.command
            continue_on_error: true
            data:
              entity_id: !input tv_entity
              command: com.webos.service.tvpower/power/turnOnScreen
